### ISSUE TITLE
debian x64 - make - can't make Glute.pas

### ISSUE THREAD

**Issue by markfirmware** [blippy/ultimc#1]
root@localhost:~/github.com/blippy/ultimc# make
    fpc  GimpPpm.pas GimpPpmTest.pas
    Warning: Only one source file supported, changing source file to compile from "GimpPpm.pas" into 
    "GimpPpmTest.pas"
    Free Pascal Compiler version 3.1.1 [2018/09/08] for x86_64
    Copyright (c) 1993-2015 by Florian Klaempfl and others
    Target OS: Linux for x86-64
    Compiling GimpPpmTest.pas
    Compiling GimpPpm.pas
    Linking GimpPpmTest
    90 lines compiled, 0.2 sec
    1 warning(s) issued
    make: *** No rule to make target 'Glute.pas', needed by 'GluteTest'.  Stop.
    root@localhost:~/github.com/blippy/ultimc#

**Comment by blippy** [comment]
I didn't think anyone would try it out so quickly.

Don't use the Makefile. I'm thinking of, maybe, removing it. Launch the ultimc.lpr project using the Ultibo-customised version of Lazarus, and compile it. Hopefully that should work.

If you just want the Forth to be hosted on your platform, then use the lpr file in the ForthIntel directory using regular Lazarus. It works on Linux x86_64 (at least for me), and I expect that it should work for Raspbian.

The keyboard is set for UK. I can work around that if you're keen, though.

**Comment by markfirmware** [comment]
lazbuild ultimc.lpi

This works but I don't have a pi at hand. Would you consider a pull request that adds $ifdef so that a qemu version can be built and run on the host? Cheers, Mark

**Comment by blippy** [comment]
Sure. 

I did toy with QEMU a few days ago. It might not work though. The problem boils down to QEMU not emulating a lot of Pi stuff. You might want to create a simple "hello world" project not based on Ultimc to see if it works in principle. I think Ultibo may use stuff that QEMU doesn't emulate, so you might find yourself falling at the first hurdle. 

A further point: QEMU is only just beginning to implement Pi3-specific stuff. I'd be happy to "downgrade" the project to use Pi2, as a Pi2 should be plenty beefy enough to run the Forth. 

I'll investigate a little further to see if QEMU stands much of a chance of working. The little experiment I did suggested that QEMU wasn't up to snuff, but we may not be completely dead in the water yet.

**Comment by markfirmware** [comment]
Ultibo does suppprt the arm versatile platform board under qemu, not the rpi2 or rpi3 emulations.

See the middle part of https://ultibo.org/forum/viewtopic.php?f=4&t=377&p=1857&hilit=Qemuvpb#p1857

It is true that qemu doesn't have a lot of what a pi has but it does have networking, keyboard/mouse/disolay, and serial i/o.

**Comment by blippy** [comment]
Interesting. I might have a go at splitting out some of the RPi stuff to see if I can get it to work on a "commodity ARM". The idea of getting a Forth to work in a tiny retro environment is appealing. The smaller the better, for that ZX81 feel.

Are you the guy that runs the Ultibo project, BTW?

**Comment by markfirmware** [comment]
No, I don't run Ultibo, but I am an enthusiast. I'll make that pr for building for qemuvpb. Mark.

**Comment by blippy** [comment]
Good news: I have been able to get it to working with qemuvpb. Use the `fipq.lpi` project to build a `kernel.bin`. 

To run it, issue a command like:
`qemu-system-arm -machine versatilepb -cpu cortex-a8 -m 256M kernel.bin`

I had been able to mount a disk image with it recently, although it now seems to not work. This is a pity, because some extra words like `CONSTANT`, which are defined in `core.4th`, can't be loaded. Sigh. I might make a workaround mechanism for that. 

Looking on the upside, though, that does mean that it can run on a diskless machine. In theory, anyway. I have no idea if anyone would want to do that, or how they'd get the image to boot, but hey-ho.

**Comment by blippy** [comment]
Disk images are now supported on QEMU. Take a look at 
https://github.com/blippy/ultimc/tree/master/fipq
Getting up and running with QEMU should now be relatively painless, as I've ironed out most of the wrinkles in getting the whole thing running.

**Comment by markfirmware** [comment]
FYI a pattern for multiple ultibo targets https://ultibo.org/forum/viewtopic.php?f=10&t=1195

**Comment by blippy** [comment]
I think this issue can be closed now. Do you agree?
