### ISSUE TITLE
Text cursor is not displayed

### ISSUE THREAD

**Issue by markfirmware** [blippy/ultimc#2]
It would help text entry to see a text cursor. Regard, Mark.

**Comment by markfirmware** [comment]
See "Text Caret Support" in https://ultibo.org/forum/viewtopic.php?f=4&t=1038&p=6900&hilit=text+cursor#p6900

**Comment by blippy** [comment]
Can I close this issue?

**Comment by markfirmware** [comment]
Will test later this morning, thanks!

**Comment by markfirmware** [comment]
Tested on qemu/ultibo/lazarus/win10 Thanks!
