### ISSUE TITLE
Pi keyboard and drive not working

### ISSUE THREAD

**Issue by blippy** [blippy/ultimc#7]
The keyboard isn't working, and the hard drive mounting fails. Recent commits seem the likely suspects. Maybe something to do with the serial port additions?

**Comment by markfirmware** [comment]
Will examine when I get to my lab later today.

**Comment by blippy** [comment]
I should clarify by saying that the problem manifests on the Pi's, not QEMU. Having said that, I've taken a look at your code, and there doesn't look to be anything that could create a problem.

On a different note, we'll probably have to define some kind of mechanism for reading the serial port.  You can see this in parser.pas line 350. There's a conditional compile dependent upon whether an ARM version is being compiled, or not. I think it should be possible to eliminate the conditional compilation. I would, in effect, just get rid of readln(tib), and just use ReadLinePtr that tied itself to readln(). 

That way, the serial port that you are working to just fills in the pointer with its own mechanism.

I'm probably not making much sense, am I? Let me know if you're a bit confused.

**Comment by blippy** [comment]
In commit https://github.com/blippy/ultimc/commit/9da65a57ceb9870266a03fac6853e9569669c9f3 I made it so that non-file reads call ReadLinePtr(). It defaults to StdReadLn() (effectively just readln()), meaning that it works in the normal way under Windows and Linux. But the ARM version sets ReadLinePtr to @ReadLnConsole, meaning that input is read from the Console.

In your Serial API, you'll probably want to do something similar, I presume; setting ReadLinePtr to some kind of serial equivalent.

**Comment by blippy** [comment]
MF, I have done some updates which should facilitate the ShellForth integration. The idea is that the shell calls Forth as if it was a regular program. To exit the Forth, you'd just type BYE, which should bring you back to the shell.

I have created a branch with my experiments:
https://github.com/blippy/ultimc/tree/shell

The writing side works, but not the reading. I'm not sure what the problem is. The parser contains two hooks: WritePtr() for writing to the shell, and ReadLinePtr() for reading a line from the shell. The calling program needs to hook their custom versions for writing and reading.

On the writing side, ShellForth sets:
`WritePtr := ShellForthWritePtr;`
which basically calls the shells DoOutput. So far so good.

On the reading side, ShellForth sets:
`ReadLinePtr := @ShellForthReadLnPtr;`
which calls DoInput under the hood. Except that DoInput doesn't seem to actually be doing a readln. What is going wrong is something I can't fathom. 

I don't think there's necessarily anything wrong with the parser itself, it's that TShell or TShellSession isn't doing DoInput(), or else it's working in a way I miscomprehend.

Any thoughts on this?

**Comment by markfirmware** [comment]
https://github.com/markfirmware/ultimc/releases/tag/v2.2018.10.02.1340

This release is from the shell branch and the keyboard and text cursor work well on an rpi3b+.

Regard, @markfirmware

**Comment by blippy** [comment]
Very nice. Works fine. Keyboard and drive work fine, too. This issue can be closed in that regard, although we still have the TShell problems to sort out.

Have you tried the `editor` command BTW? You can edit files in a graphical environment. You might like to try creating the file pattern.4th from within the editor:
```
# PRINT A TEST PATTERN
# X Y W H COL
0 0 850 700 99 FBRECT # blue square
600 50 400 600 990000 FBRECT # red square
100 100 600 500 9900 FBRECT # green square
```

and running it from the repl:
```
include pattern.4th
```

**Comment by markfirmware** [comment]
Pi keyboard and drive are working. Go ahead and close this issue.
